# See https://zellwk.com/blog/github-actions-deploy/ an explanation of this code
name: deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - run: echo hello > world.txt

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: world.txt

      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: distfiles
      
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: distfiles/*
          target: "bot"
